name: shop_project
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  intl: ^0.20.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  flutter_cart: ^0.0.9
  salomon_bottom_bar: ^3.3.2
  http: ^1.2.2
  provider: ^6.1.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_notifications_handler: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Monstserrat
      fonts:
        - asset: assets/fonts/Montserrat,Playfair_Display/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat,Playfair_Display/Montserrat/Montserrat-VariableFont_wght.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Montserrat,Playfair_Display/Playfair_Display/PlayfairDisplay-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat,Playfair_Display/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
